name = "dolar-al-dia-api"
main = "src/index.js"
compatibility_date = "2026-08-01"

# Reemplaza el id con el que te da:
# wrangler kv namespace create RATES_KV
[[kv_namespaces]]
binding = "RATES_KV"
id = "89925570929c4b25b4bff9e1e1d23745"

# Refresca BCV + USDT cada 15 minutos.
[triggers]
crons = ["*/15 * * * *"]
